---
driver:
  name: ssh_gzip
# set to ssh private key
  ssh_key: spec/test.pem
  username: centos
  sudo: true

provisioner:
  name: ansible_playbook
  roles_path: roles
  ansible_connection: ssh
  private_key: spec/test.pem
  ansible_inventory: inventory/hosts_ssh
  ansible_host_key_checking: false
  ansible_verbose: true
  ansible_verbosity: 4
  require_chef_for_busser: false
  requirements_path: requirements.yml

platforms:
  - name: centos-7.0

verifier:
  name: serverspec
  sudo_path: true
# set to true to run serverspec on your workstation
#  remote_exec: false

suites:
  - name: ansible
    driver_config:
      hostname: '52.16.196.201'
    verifier:
      default_pattern: true
#      patterns:
#      - roles/xxxx/spec/xxxxxx_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
      env_vars:
        TARGET_HOST: 127.0.0.1
        LOGIN_USER: centos
        SUDO: true
# set to ssh private key
        SSH_KEY: spec/test.pem